# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "pdb2pqr"
description: |
  Convert PDB files to PQR format by
  assigning charge and radius parameters for
  electrostatics calculations (e.g. APBS input preparation).
keywords:
  - structure
  - protein
  - electrostatics
  - pdb
  - pqr
tools:
  - "pdb2pqr":
      description: |
        PDB2PQR converts protein structure files in PDB format to PQR format by assigning
        atomic charges and radii. It is commonly used to prepare structures for
        electrostatics calculations with APBS.
      homepage: "https://www.poissonboltzmann.org"
      documentation: "https://pdb2pqr.readthedocs.io"
      tool_dev_url: "https://github.com/Electrostatics/pdb2pqr"
      doi: "10.1002/pro.3280"
      licence: ["Custom"]
      identifier: biotools:PDB2PQR

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - pdb:
        type: file
        description: Protein structure file in PDB format
        pattern: "*.{pdb}"
        ontologies:
          - edam: "http://edamontology.org/format_1476" # PDB

output:
  pqr:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
      - "*.pqr":
          type: file
          description: Protein structure file in PQR format
          pattern: "*.pqr"
  conf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
      - "*.in":
          type: file
          description: APBS input configuration file generated by PDB2PQR
          pattern: "*.in"
  log:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
      - "*.log":
          type: file
          description: Log file produced during PDB2PQR execution
          pattern: "*.log"
          ontologies:
            - edam: "http://edamontology.org/format_2330" # Textual format
  versions_pdb2pqr:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "pdb2pqr":
          type: string
          description: The name of the tool
      - "pdb2pqr --version | sed 's/^[^ ]* //'":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pdb2pqr:
          type: string
          description: The name of the tool
      - pdb2pqr --version | sed 's/^[^ ]* //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@vagkaratzas"
maintainers:
  - "@vagkaratzas"
