name: "strobealign"
description: "Align short reads using dynamic seed size with strobemers"
keywords:
  - strobealign
  - strobemers
  - alignment
  - map
  - fastq
  - bam
  - sam
tools:
  - "strobealign":
      description: "Align short reads using dynamic seed size with strobemers"
      homepage: "https://github.com/ksahlin/strobealign"
      documentation: "https://github.com/ksahlin/strobealign?tab=readme-ov-file#usage"
      tool_dev_url: "https://github.com/ksahlin/strobealign"
      doi: "10.1186/s13059-022-02831-7"
      licence:
        - "MIT"
      identifier: biotools:strobealign
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
          List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively.
        ontologies:
          - edam: "http://edamontology.org/data_2044"
          - edam: "http://edamontology.org/format_1930"
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: Reference genome in FASTA format
        pattern: "*.{fasta,fa}"
        ontologies:
          - edam: "http://edamontology.org/data_2044"
          - edam: "http://edamontology.org/format_1929"
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test', single_end:false ]
    - index:
        type: file
        description: Strobealign genome index file
        pattern: "*.sti"
        ontologies:
          - edam: "http://edamontology.org/data_3210"
  - sort_bam:
      type: boolean
      description: use samtools sort (true) or samtools view (false)
      pattern: "true or false"
output:
  bam:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.bam":
          type: file
          description: Output BAM file containing read alignments
          pattern: "*.{bam}"
          ontologies:
            - edam: "http://edamontology.org/format_2572"
  cram:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.cram":
          type: file
          description: Output CRAM file containing read alignments
          pattern: "*.{cram}"
          ontologies:
            - edam: "http://edamontology.org/format_3462"
  csi:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.csi":
          type: file
          description: Optional index file for BAM file
          pattern: "*.{csi}"
          ontologies: []
  crai:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.crai":
          type: file
          description: Optional index file for CRAM file
          pattern: "*.{crai}"
          ontologies: []
  paf:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.paf.gz":
          type: file
          description: Output PAF file containing read alignments
          pattern: "*.{paf.gz}"
          ontologies: []
  tsv:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.tsv.gz":
          type: file
          description: Output TSV file containing read alignments
          pattern: "*.{tsv.gz}"
          ontologies:
            - edam: "http://edamontology.org/format_3475"
  sti:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.sti":
          type: file
          description: Optional strobealign index file for fasta reference
          pattern: "*.{sti}"
          ontologies: []
  versions_strobealign:
    - - ${task.process}:
          type: string
          description: The name of the process
      - strobealign:
          type: string
          description: The name of the tool
      - strobealign --version:
          type: eval
          description: The expression to obtain the version of the tool
  versions_samtools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
  versions_pigz:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pigz:
          type: string
          description: The name of the tool
      - pigz --version 2>&1 | sed 's/pigz //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - strobealign:
          type: string
          description: The name of the tool
      - strobealign --version:
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - pigz:
          type: string
          description: The name of the tool
      - pigz --version 2>&1 | sed 's/pigz //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@matthdsm"
maintainers:
  - "@matthdsm"
  - "@nvnieuwk"
