name: "picard_collectrnaseqmetrics"
description: Collect metrics from a RNAseq BAM file
keywords:
  - rna
  - bam
  - metrics
  - alignment
  - statistics
  - quality
tools:
  - "picard":
      description: |
        A set of command line tools (in Java) for manipulating high-throughput sequencing (HTS)
        data and formats such as SAM/BAM/CRAM and VCF.
      homepage: "https://broadinstitute.github.io/picard/"
      documentation: "https://broadinstitute.github.io/picard/"
      tool_dev_url: "https://github.com/broadinstitute/picard"
      licence: ["MIT"]
      identifier: biotools:picard_tools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false, strandedness:true ]
    - bam:
        type: file
        description: BAM/SAM file
        pattern: "*.{bam,sam}"
        ontologies: []
  - ref_flat:
      type: file
      description: Genome ref_flat file
      ontologies: []
  - fasta:
      type: file
      description: Genome fasta file
      ontologies: []
  - rrna_intervals:
      type: file
      description: Interval file of ribosomal RNA regions
      ontologies: []
output:
  metrics:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.rna_metrics":
          type: file
          description: RNA alignment metrics files generated by picard
          pattern: "*.rna_metrics"
          ontologies: []
  pdf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.pdf":
          type: file
          description: Plot normalized position vs. coverage in a pdf file generated
            by picard
          ontologies: []
  versions_picard:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - picard:
          type: string
          description: The tool name
      - "picard CollectRnaSeqMetrics --version 2>&1 | sed -n 's/.*Version://p'":
          type: string
          description: The command used to generate the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - picard:
          type: string
          description: The tool name
      - "picard CollectRnaSeqMetrics --version 2>&1 | sed -n 's/.*Version://p'":
          type: string
          description: The command used to generate the version of the tool
authors:
  - "@anoronh4"
maintainers:
  - "@anoronh4"
