name: picard_sortsam
description: Sorts BAM/SAM files based on a variety of picard specific criteria
keywords:
  - sort
  - bam
  - sam
  - picard
tools:
  - picard:
      description: |
        A set of command line tools (in Java) for manipulating high-throughput sequencing (HTS)
        data and formats such as SAM/BAM/CRAM and VCF.
      homepage: https://broadinstitute.github.io/picard/
      documentation: https://broadinstitute.github.io/picard/
      licence: ["MIT"]
      identifier: biotools:picard_tools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: BAM/CRAM/SAM file
        pattern: "*.{bam,sam}"
        ontologies: []
  - sort_order:
      type: string
      description: Picard sort order type
      pattern: "unsorted|queryname|coordinate|duplicate|unknown"
output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bam":
          type: file
          description: Sorted BAM/CRAM/SAM file
          pattern: "*.{bam}"
          ontologies: []
  versions_picard:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - picard:
          type: string
          description: The tool name
      - "picard SortSam --version 2>&1 | sed -n 's/.*Version://p'":
          type: string
          description: The command used to generate the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - picard:
          type: string
          description: The tool name
      - "picard SortSam --version 2>&1 | sed -n 's/.*Version://p'":
          type: string
          description: The command used to generate the version of the tool
authors:
  - "@jfy133"
maintainers:
  - "@jfy133"
