name: picard_mergesamfiles
description: Merges multiple BAM files into a single file
keywords:
  - merge
  - alignment
  - bam
  - sam
tools:
  - picard:
      description: |
        A set of command line tools (in Java) for manipulating high-throughput sequencing (HTS)
        data and formats such as SAM/BAM/CRAM and VCF.
      homepage: https://broadinstitute.github.io/picard/
      documentation: https://broadinstitute.github.io/picard/
      licence: ["MIT"]
      identifier: biotools:picard_tools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bams:
        type: list
        description: List of input BAM files to be merged
        pattern: "*.{bam}"
output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bam":
          type: file
          description: Merged BAM file
          pattern: "*.{bam}"
          ontologies: []
  versions_picard:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - picard:
          type: string
          description: The tool name
      - "picard MergeSamFiles --version 2>&1 | sed -n 's/.*Version://p'":
          type: string
          description: The command used to generate the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - picard:
          type: string
          description: The tool name
      - "picard MergeSamFiles --version 2>&1 | sed -n 's/.*Version://p'":
          type: string
          description: The command used to generate the version of the tool
authors:
  - "@drpatelh"
maintainers:
  - "@drpatelh"
