name: picard_createsequencedictionary
description: Creates a sequence dictionary for a reference sequence.
keywords:
  - sequence
  - dictionary
  - picard
tools:
  - picard:
      description: |
        Creates a sequence dictionary file (with ".dict" extension) from a reference sequence provided in FASTA format, which is required by many processing and analysis tools. The output file contains a header but no SAMRecords, and the header contains only sequence records.
      homepage: https://broadinstitute.github.io/picard/
      documentation: https://gatk.broadinstitute.org/hc/en-us/articles/360036712531-CreateSequenceDictionary-Picard-
      tool_dev_url: https://github.com/broadinstitute/picard
      licence: ["MIT"]
      identifier: biotools:picard_tools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: The reference fasta file
        pattern: "*.fasta"
        ontologies: []
output:
  reference_dict:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.dict":
          type: file
          description: picard dictionary file
          pattern: "*.{dict}"
          ontologies: []
  versions_picard:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - picard:
          type: string
          description: The tool name
      - "picard CreateSequenceDictionary --version 2>&1 | sed -n 's/.*Version://p'":
          type: string
          description: The command used to generate the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - picard:
          type: string
          description: The tool name
      - "picard CreateSequenceDictionary --version 2>&1 | sed -n 's/.*Version://p'":
          type: string
          description: The command used to generate the version of the tool
authors:
  - "@sateeshperi"
  - "@mjcipriano"
  - "@hseabolt"
maintainers:
  - "@sateeshperi"
  - "@mjcipriano"
  - "@hseabolt"
