name: "snapaligner_index"
description: Create a SNAP index for reference genome
keywords:
  - index
  - fasta
  - genome
  - reference
tools:
  - "snapaligner":
      description: "Scalable Nucleotide Alignment Program -- a fast and accurate read
        aligner for high-throughput sequencing data"
      homepage: "http://snap.cs.berkeley.edu"
      documentation: "https://1drv.ms/b/s!AhuEg_0yZD86hcpblUt-muHKYsG8fA?e=R8ogug"
      tool_dev_url: "https://github.com/amplab/snap"
      doi: "10.1101/2021.11.23.469039"
      licence:
        - "Apache v2"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: Input genome fasta file
        ontologies:
          - edam: http://edamontology.org/format_1929
    - altcontigfile:
        type: file
        description: Optional file with a list of alt contig names, one per line.
        ontologies:
          - edam: http://edamontology.org/format_3750
    - nonaltcontigfile:
        type: file
        description: Optional file that contains a list of contigs (one per line)
          that will not be marked ALT regardless of size.
        ontologies:
          - edam: http://edamontology.org/format_3750
    - altliftoverfile:
        type: file
        description: Optional file containing ALT-to-REF mappings (SAM format).
          e.g., hs38DH.fa.alt from bwa-kit.
        ontologies:
          - edam: http://edamontology.org/format_3750
output:
  index:
    - - meta:
          type: file
          description: SNAP genome index files
          pattern: "{Genome,GenomeIndex,GenomeIndexHash,OverflowTable}"
          ontologies: []
      - snap/*:
          type: file
          description: SNAP genome index files
          pattern: "{Genome,GenomeIndex,GenomeIndexHash,OverflowTable}"
          ontologies: []
  versions_snapaligner:
    - - ${task.process}:
          type: string
          description: The name of the process
      - snap-aligner:
          type: string
          description: The name of the tool
      - snap-aligner 2>&1 | sed 's/^.*version //;s/.\$//;q':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - snap-aligner:
          type: string
          description: The name of the tool
      - snap-aligner 2>&1 | sed 's/^.*version //;s/.\$//;q':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@matthdsm"
maintainers:
  - "@matthdsm"
