name: "somalier_relate"
description: Somalier can extract informative sites, evaluate relatedness, and
  perform quality-control on BAM/CRAM/BCF/VCF/GVCF or from jointly-called VCFs
keywords:
  - relatedness
  - QC
  - bam
  - cram
  - vcf
  - gvcf
  - ancestry
  - identity
  - kinship
  - informative sites
  - family
tools:
  - "somalier":
      description: "Somalier can extract informative sites, evaluate relatedness, and
        perform quality-control on BAM/CRAM/BCF/VCF/GVCF or from jointly-called VCFs"
      homepage: "https://github.com/brentp/somalier"
      documentation: "https://github.com/brentp/somalier/blob/master/README.md"
      tool_dev_url: "https://github.com/brentp/somalier"
      doi: "10.1186/s13073-020-00761-2"
      licence:
        - "MIT"
      identifier: biotools:somalier
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - extract:
        type: file
        description: extract file(s) from Somalier extract
        pattern: "*.somalier"
        ontologies: []
    - ped:
        type: file
        description: optional path to a ped or fam file indicating the expected
          relationships among samples
        pattern: "*.{ped,fam}"
        ontologies: []
  - sample_groups:
      type: file
      description: optional path to expected groups of samples such as tumor
        normal pairs specified as comma-separated groups per line
      pattern: "*.{txt,csv}"
      ontologies:
        - edam: http://edamontology.org/format_3752
output:
  html:
    - - meta:
          type: file
          description: html file
          pattern: "*.html"
          ontologies: []
      - "*.html":
          type: file
          description: html file
          pattern: "*.html"
          ontologies: []
  pairs_tsv:
    - - meta:
          type: file
          description: html file
          pattern: "*.html"
          ontologies: []
      - "*.pairs.tsv":
          type: file
          description: tsv file with output stats for pairs of samples
          pattern: "*.pairs.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475
  samples_tsv:
    - - meta:
          type: file
          description: html file
          pattern: "*.html"
          ontologies: []
      - "*.samples.tsv":
          type: file
          description: tsv file with sample-level information
          pattern: "*.samples.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475
  versions_somalier:
    - - ${task.process}:
          type: string
          description: The name of the process
      - somalier:
          type: string
          description: The name of the tool
      - "somalier 2>&1 | sed -n 's/.*version: \\([0-9.]*\\).*/\\1/p'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - somalier:
          type: string
          description: The name of the tool
      - "somalier 2>&1 | sed -n 's/.*version: \\([0-9.]*\\).*/\\1/p'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@ashotmarg"
  - "@nvnieuwk"
maintainers:
  - "@ashotmarg"
  - "@nvnieuwk"
