name: "freyja_update"
description: downloads new versions of the curated SARS-CoV-2 lineage file and
  barcodes
keywords:
  - database
  - variants
  - UShER
tools:
  - "freyja":
      description: "Freyja recovers relative lineage abundances from mixed SARS-CoV-2
        samples and provides functionality to analyze lineage dynamics."
      homepage: "https://github.com/andersen-lab/Freyja"
      documentation: "https://github.com/andersen-lab/Freyja/wiki"
      tool_dev_url: "https://github.com/andersen-lab/Freyja"
      doi: "10.1038/s41586-022-05049-6"
      licence:
        - "BSD-2-Clause"
      identifier: "biotools:freyja"
input:
  - db_name:
      type: string
      description: "The name of the database directory"
output:
  barcodes:
    - "${db_name}/*barcodes.*":
        type: file
        description: File containing lineage defining barcodes
        pattern: "*barcodes.csv"
        ontologies:
          - edam: http://edamontology.org/format_3752 # CSV
  lineages_topology:
    - "${db_name}/*lineages.yml":
        type: file
        description: File containing lineage topology information that correspond to barcodes
        pattern: "*lineages.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
  lineages_meta:
    - "${db_name}/*curated_lineages.json":
        type: file
        description: File containing lineage metadata that correspond to barcodes
        pattern: "*curated_lineages.json"
        ontologies:
          - edam: http://edamontology.org/format_3464 # JSON
  config:
    - "${db_name}/*pathogen_config.yml":
        type: file
        description: File containing pathogen configuration information for Freyja
        pattern: "*pathogen_config.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
  versions_freyja:
    - - ${task.process}:
          type: string
          description: The name of the process
      - freyja:
          type: string
          description: The name of the tool
      - freyja --version | sed 's/.* //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - freyja:
          type: string
          description: The name of the tool
      - freyja --version | sed 's/.* //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@Joon-Klaps"
maintainers:
  - "@Joon-Klaps"
