name: "md5sum"
description: Create MD5 (128-bit) checksums
keywords:
  - checksum
  - MD5
  - 128 bit
tools:
  - "md5sum":
      description: Create MD5 (128-bit) checksums for each file
      homepage: "https://www.gnu.org"
      documentation: "https://man7.org/linux/man-pages/man1/md5sum.1.html"
      licence:
        - "GPL-3.0-or-later"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - files:
        type: file
        description: Any number of files. One md5sum file will be generated for
          each.
        pattern: "*.*"
        ontologies: []
  - as_separate_files:
      type: boolean
      description: |
        If true, each file will have its own md5sum file. If false, all files will be
        checksummed into a single md5sum file.
output:
  checksum:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.md5":
          type: file
          description: File containing checksum
          pattern: "*.md5"
          ontologies: []
  versions_md5sum:
    - - ${task.process}:
          type: string
          description: The name of the process
      - md5sum:
          type: string
          description: The name of the tool
      - md5sum --version | sed '1!d; s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - md5sum:
          type: string
          description: The name of the tool
      - md5sum --version | sed '1!d; s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@matthdsm"
maintainers:
  - "@matthdsm"
