name: dragmap_hashtable
description: Create DRAGEN hashtable for reference genome
keywords:
  - index
  - fasta
  - genome
  - reference
tools:
  - dragmap:
      description: Dragmap is the Dragen mapper/aligner Open Source Software.
      homepage: https://github.com/Illumina/dragmap
      documentation: https://github.com/Illumina/dragmap
      tool_dev_url: https://github.com/Illumina/dragmap#basic-command-line-usage
      licence:
        - "GPL v3"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: Input genome fasta file
        ontologies:
          - edam: http://edamontology.org/format_1929
output:
  hashmap:
    - - meta:
          type: map
          description: |
            Groovy Map containing reference information
            e.g. [ id:'test', single_end:false ]
      - dragmap:
          type: string
          description: DRAGMAP hash table
          pattern: "*.{cmp,.bin,.txt}"
          ontologies: []
  versions_dragmap:
    - - ${task.process}:
          type: string
          description: The name of the process
      - dragmap:
          type: string
          description: DRAGMAP hash table
          pattern: "*.{cmp,.bin,.txt}"
          ontologies: []
      - dragen-os --version 2>&1:
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - dragmap:
          type: string
          description: DRAGMAP hash table
          pattern: "*.{cmp,.bin,.txt}"
          ontologies: []
      - dragen-os --version 2>&1:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@edmundmiller"
maintainers:
  - "@edmundmiller"
