name: "freyja_variants"
description: call variant and sequencing depth information of the variant
keywords:
  - variants
  - fasta
  - wastewater
tools:
  - "freyja":
      description: "Freyja recovers relative lineage abundances from mixed SARS-CoV-2
        samples and provides functionality to analyze lineage dynamics."
      homepage: "https://github.com/andersen-lab/Freyja"
      documentation: "https://github.com/andersen-lab/Freyja/wiki"
      tool_dev_url: "https://github.com/andersen-lab/Freyja"
      doi: "10.1038/s41586-022-05049-6"
      licence:
        - "BSD-2-Clause"
      identifier: "biotools:freyja"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test' ]
    - bam:
        type: file
        description: Sorted BAM file
        pattern: "*.bam"
        ontologies: []
  - fasta:
      type: file
      description: The reference sequence used for mapping and generating the BAM
        file
      pattern: "*.fa"
      ontologies: []
output:
  variants:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - "*.variants.tsv":
          type: file
          description: File containing identified variants in a gff-like format
          pattern: "*.variants.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV
      - "*.depth.tsv":
          type: file
          description: File containing depth of the variants
          pattern: "*.depth.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV
  versions_freyja:
    - - ${task.process}:
          type: string
          description: The name of the process
      - freyja:
          type: string
          description: The name of the tool
      - freyja --version | sed 's/.* //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - freyja:
          type: string
          description: The name of the tool
      - freyja --version | sed 's/.* //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@Joon-Klaps"
maintainers:
  - "@Joon-Klaps"
