name: "somalier_extract"
description: Somalier can extract informative sites, evaluate relatedness, and
  perform quality-control on BAM/CRAM/BCF/VCF/GVCF or from jointly-called VCFs
keywords:
  - relatedness
  - QC
  - bam
  - cram
  - vcf
  - gvcf
  - ancestry
  - identity
  - kinship
  - informative sites
  - family
tools:
  - "somalier":
      description: "Somalier can extract informative sites, evaluate relatedness, and
        perform quality-control on BAM/CRAM/BCF/VCF/GVCF or from jointly-called VCFs"
      homepage: "https://github.com/brentp/somalier"
      documentation: "https://github.com/brentp/somalier/blob/master/README.md"
      tool_dev_url: "https://github.com/brentp/somalier"
      doi: "10.1186/s13073-020-00761-2"
      licence:
        - "MIT"
      identifier: biotools:somalier
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: BAM/CRAM/SAM/BCF/VCF/GVCF or jointly-called VCF file
        ontologies: []
    - input_index:
        type: file
        description: index file of the input data, e.g., bam.bai, cram.crai
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'hg38' ]
    - fasta:
        type: file
        description: The reference fasta file
        pattern: "*.{fasta,fna,fas,fa}"
        ontologies: []
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'hg38' ]
    - fai:
        type: file
        description: FASTA index file
        pattern: "*.fai"
        ontologies: []
  - - meta4:
        type: map
        description: |
          Groovy Map containing sites information
          e.g. [ id:'hg38' ]
    - sites:
        type: file
        description: sites file in VCF format which can be taken from
          https://github.com/brentp/somalier
        pattern: "*.vcf.gz"
        ontologies:
          - edam: http://edamontology.org/format_3989
output:
  extract:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.somalier":
          type: file
          description: binary output file based on extracted sites
          pattern: "*.{somalier}"
          ontologies: []
  versions_somalier:
    - - ${task.process}:
          type: string
          description: The name of the process
      - somalier:
          type: string
          description: The name of the tool
      - "somalier 2>&1 | sed -n 's/.*version: \\([0-9.]*\\).*/\\1/p'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - somalier:
          type: string
          description: The name of the tool
      - "somalier 2>&1 | sed -n 's/.*version: \\([0-9.]*\\).*/\\1/p'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@ashotmarg"
  - "@nvnieuwk"
maintainers:
  - "@ashotmarg"
  - "@nvnieuwk"
