name: msisensorpro_scan
description: MSIsensor-pro evaluates Microsatellite Instability (MSI) for cancer
  patients with next generation sequencing data. It accepts the whole genome
  sequencing, whole exome sequencing and target region (panel) sequencing data
  as input
keywords:
  - micro-satellite-scan
  - msisensor-pro
  - scan
tools:
  - msisensorpro:
      description: Microsatellite Instability (MSI) detection using
        high-throughput sequencing data.
      homepage: https://github.com/xjtu-omics/msisensor-pro
      documentation: https://github.com/xjtu-omics/msisensor-pro/wiki
      tool_dev_url: https://github.com/xjtu-omics/msisensor-pro
      doi: "10.1016/j.gpb.2020.02.001"
      licence:
        - "Custom Licence"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: Reference genome
        pattern: "*.{fasta}"
        ontologies: []
output:
  list:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.list":
          type: file
          description: File containing microsatellite list
          pattern: "*.{list}"
          ontologies: []
  versions_msisensorpro:
    - - ${task.process}:
          type: string
          description: The name of the process
      - msisensor-pro:
          type: string
          description: The name of the tool
      - msisensor-pro --version 2>&1 | sed -nE 's/Version:\s*//p':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - msisensor-pro:
          type: string
          description: The name of the tool
      - msisensor-pro --version 2>&1 | sed -nE 's/Version:\s*//p':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@FriederikeHanssen"
maintainers:
  - "@FriederikeHanssen"
