name: dragmap_align
description: Performs fastq alignment to a reference using DRAGMAP
keywords:
  - alignment
  - map
  - fastq
  - bam
  - sam
tools:
  - dragmap:
      description: Dragmap is the Dragen mapper/aligner Open Source Software.
      homepage: https://github.com/Illumina/dragmap
      documentation: https://github.com/Illumina/dragmap
      tool_dev_url: https://github.com/Illumina/dragmap#basic-command-line-usage
      licence:
        - "GPL v3"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
          List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively.
        ontologies:
          - edam: http://edamontology.org/format_1930
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'test', single_end:false ]
    - hashmap:
        type: file
        description: DRAGMAP hash table
        pattern: "Directory containing DRAGMAP hash table *.{cmp,.bin,.txt}"
        ontologies: []
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome']
    - fasta:
        type: file
        description: Genome fasta reference files
        pattern: "*.{fa,fasta,fna}"
        ontologies:
          - edam: http://edamontology.org/format_1929
  - sort_bam:
      type: boolean
      description: Sort the BAM file
output:
  sam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.sam":
          type: file
          description: Output SAM file containing read alignments
          pattern: "*.{sam}"
          ontologies:
            - edam: http://edamontology.org/format_2571
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bam":
          type: file
          description: Output BAM file containing read alignments
          pattern: "*.{bam}"
          ontologies:
            - edam: http://edamontology.org/format_2572
  cram:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.cram":
          type: file
          description: Output CRAM file containing read alignments
          pattern: "*.{cram}"
          ontologies:
            - edam: http://edamontology.org/format_2573
  crai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.crai":
          type: file
          description: Index file for CRAM file
          pattern: "*.{crai}"
          ontologies: []
  csi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.csi":
          type: file
          description: Index file for CRAM file
          pattern: "*.{csi}"
          ontologies: []
  log:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.log":
          type: file
          description: Log file
          pattern: "*.{log}"
          ontologies:
            - edam: http://edamontology.org/format_3888
  versions_dragmap:
    - - ${task.process}:
          type: string
          description: The name of the process
      - dragmap:
          type: string
          description: The name of the tool
      - dragen-os --version 2>&1:
          type: eval
          description: The expression to obtain the version of the tool
  versions_samtools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
  versions_pigz:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pigz:
          type: string
          description: The name of the tool
      - pigz --version 2>&1 | sed 's/pigz //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - dragmap:
          type: string
          description: The name of the tool
      - dragen-os --version 2>&1:
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - pigz:
          type: string
          description: The name of the tool
      - pigz --version 2>&1 | sed 's/pigz //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@edmundmiller"
maintainers:
  - "@edmundmiller"
