name: "elprep_fastatoelfasta"
description: Convert a file in FASTA format to the ELFASTA format
keywords:
  - fasta
  - elfasta
  - elprep
tools:
  - "elprep":
      description: "elPrep is a high-performance tool for preparing .sam/.bam files
        for variant calling in sequencing pipelines. It can be used as a drop-in replacement
        for SAMtools/Picard/GATK4."
      homepage: "https://github.com/ExaScience/elprep"
      documentation: "https://github.com/ExaScience/elprep"
      tool_dev_url: "https://github.com/ExaScience/elprep"
      doi: "10.1371/journal.pone.0244471"
      licence:
        - "AGPL v3"
      identifier: biotools:elprep
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - fasta:
        type: file
        description: FASTA file
        pattern: "*.{fasta,fa,fna}"
        ontologies: []
output:
  elfasta:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
          pattern: "*.elfasta"
      - "*.elfasta":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
          pattern: "*.elfasta"
  log:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
          pattern: "*.elfasta"
      - logs/elprep/elprep*:
          type: file
          description: ELFasta log file
          pattern: "*.log"
          ontologies: []
  versions_elprep:
    - - ${task.process}:
          type: string
          description: The name of the process
      - elprep:
          type: string
          description: The name of the tool
      - elprep 2>&1 | sed -n '2s/^.*version //;s/ compiled.*$//p':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - elprep:
          type: string
          description: The name of the tool
      - elprep 2>&1 | sed -n '2s/^.*version //;s/ compiled.*$//p':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@nvnieuwk"
maintainers:
  - "@nvnieuwk"
