name: "snapaligner_align"
description: Performs fastq alignment to a fasta reference using SNAP
keywords:
  - alignment
  - map
  - fastq
  - bam
  - sam
tools:
  - "snapaligner":
      description: "Scalable Nucleotide Alignment Program -- a fast and accurate read
        aligner for high-throughput sequencing data"
      homepage: "http://snap.cs.berkeley.edu"
      documentation: "https://1drv.ms/b/s!AhuEg_0yZD86hcpblUt-muHKYsG8fA?e=R8ogug"
      tool_dev_url: "https://github.com/amplab/snap"
      doi: "10.1101/2021.11.23.469039"
      licence:
        - "Apache v2"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: List of input fastq files of size 2 for paired fastq or 1 for
          bam or single fastq
        pattern: "*.{fastq.gz,fq.gz,fastq,fq,bam}"
        ontologies:
          - edam: http://edamontology.org/format_1930
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'test', single_end:false ]
    - index:
        type: file
        description: List of SNAP genome index files
        pattern: "{Genome,GenomeIndex,GenomeIndexHash,OverflowTable}"
        ontologies: []
output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bam":
          type: file
          description: Aligned BAM file
          pattern: "*.{bam}"
          ontologies:
            - edam: http://edamontology.org/format_2572
  bai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bai":
          type: file
          description: Optional aligned BAM file index
          pattern: "*.{bai}"
          ontologies:
            - edam: http://edamontology.org/format_2572
  versions_snapaligner:
    - - ${task.process}:
          type: string
          description: The name of the process
      - snap-aligner:
          type: string
          description: The name of the tool
      - snap-aligner 2>&1 | sed 's/^.*version //;s/.\$//;q':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - snap-aligner:
          type: string
          description: The name of the tool
      - snap-aligner 2>&1 | sed 's/^.*version //;s/.\$//;q':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@matthdsm"
maintainers:
  - "@matthdsm"
  - "@delfiterradas"
  - "@sofiromano"
