name: "elprep_merge"
description: Merge split bam/sam chunks in one file
keywords:
  - bam
  - sam
  - merge
tools:
  - "elprep":
      description: "elPrep is a high-performance tool for preparing .sam/.bam files
        for variant calling in sequencing pipelines. It can be used as a drop-in replacement
        for SAMtools/Picard/GATK4."
      homepage: "https://github.com/ExaScience/elprep"
      documentation: "https://github.com/ExaScience/elprep"
      tool_dev_url: "https://github.com/ExaScience/elprep"
      doi: "10.1371/journal.pone.0244471"
      licence:
        - "AGPL v3"
      identifier: biotools:elprep
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: List of BAM/SAM chunks to merge
        pattern: "*.{bam,sam}"
        ontologies: []
output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - output/**.{bam,sam}:
          type: file
          description: Merged BAM/SAM file
          pattern: "*.{bam,sam}"
          ontologies: []
  versions_elprep:
    - - ${task.process}:
          type: string
          description: The name of the process
      - elprep:
          type: string
          description: The name of the tool
      - elprep 2>&1 | sed -n '2s/^.*version //;s/ compiled.*$//p':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - elprep:
          type: string
          description: The name of the tool
      - elprep 2>&1 | sed -n '2s/^.*version //;s/ compiled.*$//p':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@matthdsm"
maintainers:
  - "@matthdsm"
