name: "picard_meanqualitybycycle"
description: Collect metrics about the mean quality by cycle of a paired-end library.
keywords:
  - metrics
  - alignment
  - mean
  - statistics
  - bam
tools:
  - "picard":
      description: "Java tools for working with NGS data in the BAM format"
      homepage: "https://broadinstitute.github.io/picard/"
      documentation: "https://broadinstitute.github.io/picard/"
      tool_dev_url: "https://github.com/broadinstitute/picard"
      licence: ["MIT"]
      identifier: biotools:picard_tools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies: []
output:
  metrics:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.txt":
          type: file
          description: Values used by Picard to generate chart.
          pattern: "*.txt"
          ontologies: []
  pdf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.pdf":
          type: file
          description: Chart in PDF format
          pattern: "*.pdf"
          ontologies: []
  versions_picard:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - picard:
          type: string
          description: The tool name
      - "picard MeanQualityByCycle --version 2>&1 | sed -n 's/.*Version://p'":
          type: string
          description: The command used to generate the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - picard:
          type: string
          description: The tool name
      - "picard MeanQualityByCycle --version 2>&1 | sed -n 's/.*Version://p'":
          type: string
          description: The command used to generate the version of the tool
authors:
  - "@mikefeixu"
  - "@FerriolCalvet"
maintainers:
  - "@mikefeixu"
