name: "vardictjava"
description: The Java port of the VarDict variant caller
keywords:
  - variant calling
  - vcf
  - bam
  - snv
  - sv
tools:
  - "vardictjava":
      description: "Java port of the VarDict variant discovery program"
      homepage: "https://github.com/AstraZeneca-NGS/VarDictJava"
      documentation: "https://github.com/AstraZeneca-NGS/VarDictJava"
      tool_dev_url: "https://github.com/AstraZeneca-NGS/VarDictJava"
      doi: "10.1093/nar/gkw227 "
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bams:
        type: file
        description: One or two BAM files. Supply two BAM files to run Vardict in
          paired mode.
        pattern: "*.bam"
        ontologies: []
    - bais:
        type: file
        description: Index/indices of the BAM file(s)
        pattern: "*.bai"
        ontologies: []
    - bed:
        type: file
        description: BED with the regions of interest
        pattern: "*.bed"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing fasta information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: FASTA of the reference genome
        pattern: "*.{fa,fasta}"
        ontologies: []
  - - meta3:
        type: map
        description: |
          Groovy Map containing fasta information
          e.g. [ id:'test', single_end:false ]
    - fasta_fai:
        type: file
        description: The index of the FASTA of the reference genome
        pattern: "*.fai"
        ontologies: []
output:
  vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.vcf.gz":
          type: file
          description: VCF file output
          pattern: "*.vcf.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989
  versions_vardictjava:
    - - ${task.process}:
          type: string
          description: The name of the process
      - vardict-java:
          type: string
          description: The name of the tool
      - realpath \$( command -v vardict-java ) | sed 's/.*java-//;s/-.*//':
          type: eval
          description: The expression to obtain the version of the tool
  versions_var2vcfvalid:
    - - ${task.process}:
          type: string
          description: The name of the process
      - var2vcf_valid.pl:
          type: string
          description: The name of the tool
      - var2vcf_valid.pl -h | sed '2!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
  versions_htslib:
    - - ${task.process}:
          type: string
          description: The name of the process
      - htslib:
          type: string
          description: The name of the tool
      - "tabix -h 2>&1 | sed -n '2s/Version: *//p'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - vardict-java:
          type: string
          description: The name of the tool
      - realpath \$( command -v vardict-java ) | sed 's/.*java-//;s/-.*//':
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - var2vcf_valid.pl:
          type: string
          description: The name of the tool
      - var2vcf_valid.pl -h | sed '2!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - htslib:
          type: string
          description: The name of the tool
      - "tabix -h 2>&1 | sed -n '2s/Version: *//p'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@nvnieuwk"
maintainers:
  - "@nvnieuwk"
