name: "picard_extractfingerprint"
description: Computes/Extracts the fingerprint genotype likelihoods from the supplied
  file. It is given as a list of PLs at the fingerprinting sites.
keywords:
  - picard
  - extract
  - fingerprint
  - bam
tools:
  - picard:
      description: |
        A set of command line tools (in Java) for manipulating high-throughput sequencing (HTS)
        data and formats such as SAM/BAM/CRAM and VCF.
      homepage: https://broadinstitute.github.io/picard/
      documentation: https://broadinstitute.github.io/picard/
      tool_dev_url: https://github.com/broadinstitute/picard/
      licence: ["MIT"]
      identifier: biotools:picard_tools
input:
  - - meta:
        type: file
        description: |
          Input SAM/BAM/CRAM file
        ontologies: []
    - bam:
        type: file
        description: BAM file
        pattern: "*.{bam}"
        ontologies: []
    - bai:
        type: file
        description: BAM index file
        pattern: "*.{bai}"
        ontologies: []
  - haplotype_map:
      type: file
      description: |
        A file of haplotype information. The file lists a set of SNPs, optionally arranged in high-LD blocks, to be used for fingerprinting.
        See https://software.broadinstitute.org/gatk/documentation/article?id=9526 for details.
      pattern: "*.{txt,vcf,vcf.gz}"
      ontologies: []
  - fasta:
      type: file
      description: Reference sequence file
      pattern: "*.{fasta,fna,fa}"
      ontologies: []
  - fasta_fai:
      type: file
      description: Reference sequence index file
      pattern: "*.{fai}"
      ontologies: []
  - sequence_dictionary:
      type: file
      description: Reference sequence dictionary file
      ontologies: []
output:
  vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.vcf.gz":
          type: file
          description: VCF file
          pattern: "*.vcf.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  tbi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.vcf.gz.tbi":
          type: file
          description: Tabix index file
          pattern: "*.vcf.gz.tbi"
          ontologies: []
  versions_picard:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - picard:
          type: string
          description: The tool name
      - "picard ExtractFingerprint --version 2>&1 | sed -n 's/.*Version://p'":
          type: string
          description: The command used to generate the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - picard:
          type: string
          description: The tool name
      - "picard ExtractFingerprint --version 2>&1 | sed -n 's/.*Version://p'":
          type: string
          description: The command used to generate the version of the tool
authors:
  - "@adamrtalbot"
  - "@mauro-saporita"
maintainers:
  - "@adamrtalbot"
  - "@mauro-saporita"
