name: "paraphase"
description: "HiFi-based caller for highly homologous genes"
keywords:
  - paraphase
  - long-read
  - HiFi
tools:
  - "paraphase":
      description: "HiFi-based caller for highly homologous genes"
      homepage: "https://github.com/PacificBiosciences/paraphase"
      documentation: "https://github.com/PacificBiosciences/paraphase"
      tool_dev_url: "https://github.com/PacificBiosciences/paraphase"
      doi: "10.1016/j.ajhg.2023.01.001"
      licence:
        - "BSD-3-clause-Clear"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:true ]`
    - bam:
        type: file
        description: Sorted BAM file
        pattern: "*.bam"
        ontologies: []
    - bai:
        type: file
        description: Index of BAM file
        pattern: "*.bai"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - fasta:
        type: file
        description: The reference fasta file
        pattern: "*.fasta"
        ontologies: []
  - - meta3:
        type: map
        description: |
          Groovy Map containing config information
          e.g. [ id:'config' ]
    - config:
        type: file
        description: Config file
        pattern: "*.yaml"
        ontologies:
          - edam: http://edamontology.org/format_3750
output:
  json:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:true ]`
      - "*.paraphase.json":
          type: file
          description: Summary of haplotype and variant calls
          pattern: "*.paraphase.json"
          ontologies:
            - edam: http://edamontology.org/format_3464
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:true ]`
      - "*.paraphase.bam":
          type: file
          description: (re)aligned BAM file
          pattern: "*.paraphase.bam"
          ontologies: []
  bai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:true ]`
      - "*.paraphase.bam.bai":
          type: file
          description: Index of (re)aligned BAM file
          pattern: "*.paraphase.bam.bai"
          ontologies: []
  vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:true ]`
      - ${prefix}_paraphase_vcfs/*.vcf.gz:
          type: file
          description: compressed VCF file(s) per gene
          pattern: "*.vcf.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989
  vcf_index:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:true ]`
      - ${prefix}_paraphase_vcfs/*.vcf.gz.{csi,tbi}:
          type: file
          description: compressed VCF file index
          pattern: "*.vcf.gz.{tbi,csi}"
          ontologies: []
  versions_minimap2:
    - - ${task.process}:
          type: string
          description: The name of the process
      - minimap2:
          type: string
          description: The name of the tool
      - minimap2 --version:
          type: eval
          description: The expression to obtain the version of the tool
  versions_paraphase:
    - - ${task.process}:
          type: string
          description: The name of the process
      - paraphase:
          type: string
          description: The name of the tool
      - paraphase --version:
          type: eval
          description: The expression to obtain the version of the tool
  versions_samtools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools --version:
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - minimap2:
          type: string
          description: The name of the tool
      - minimap2 --version:
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - paraphase:
          type: string
          description: The name of the tool
      - paraphase --version:
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools --version:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@fellen31"
maintainers:
  - "@fellen31"
